[package]
name = "bacon-ls"
version = "0.6.0-dev"
edition = "2021"
authors = ["Matteo Bigoi <bigo@crisidev.org>"]
description = "Bacon Language Server"
documentation = "https://github.com/crisidev/bacon-ls"
readme = "README.md"
homepage = "https://github.com/crisidev/bacon-ls"
repository = "https://github.com/crisidev/bacon-ls"
license-file = "LICENSE"
keywords = ["lsp", "bacon", "tokio", "neovim", "vim"]
categories = [
    "command-line-utilities",
    "text-editors",
    "asynchronous",
    "development-tools",
]

[dependencies]
argh = "0.1.13"
tokio = { version = "1.42.0", features = [
    "macros",
    "rt-multi-thread",
    "io-std",
    "io-util",
    "fs",
    "time",
] }
tower-lsp = "0.20.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
    "env-filter",
    "fmt",
] }

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace"] }
httparse = "1.9.5"
similar-asserts = "1.6.0"
pretty_assertions = "1.4.1"
