[package]
name = "bacon-ls"
version = "0.11.0-dev"
edition = "2021"
authors = ["Matteo Bigoi <bigo@crisidev.org>"]
description = "Bacon Language Server"
documentation = "https://github.com/crisidev/bacon-ls"
readme = "README.md"
homepage = "https://github.com/crisidev/bacon-ls"
repository = "https://github.com/crisidev/bacon-ls"
license-file = "LICENSE"
keywords = ["lsp", "bacon", "tokio", "neovim", "vim"]
categories = [
    "command-line-utilities",
    "text-editors",
    "asynchronous",
    "development-tools",
]

[dependencies]
argh = "0.1.13"
tokio = { version = "1.43.0", features = [
    "fs",
    "io-std",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
    "time",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"
toml = "0.8"
tower-lsp = "0.20.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
    "env-filter",
    "fmt",
] }

[dev-dependencies]
pretty_assertions = "1.4.1"
tempdir = "0.3.7"
